---
Name: fulltextsearchconfig
---
SilverStripe\ORM\DataObject:
  extensions:
    searchupdater: SilverStripe\FullTextSearch\Search\Extensions\SearchUpdater_ObjectHandler

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    fulltextsearchcontrol: SilverStripe\FullTextSearch\Solr\Control\ContentControllerExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\FullTextSearch\Search\Queries\SearchQuery:
    calls:
      - [ setHandler, [ '%$SilverStripe\FullTextSearch\Search\Adapters\SolrSearchAdapter' ]]

SilverStripe\Dev\Tasks\MigrateFileTask:
  extensions:
    disableindexingonfilemigration: SilverStripe\FullTextSearch\Search\Extensions\DisableIndexingOnFileMigration

SilverStripe\Cli\Sake:
  commands:
    - SilverStripe\FullTextSearch\Solr\Tasks\Solr_Configure
    - SilverStripe\FullTextSearch\Solr\Tasks\Solr_Reindex
